server:
  port: 8095

spring:
  datasource:
    url: jdbc:mysql://123.249.43.16:3306/bs_supermarket_jxc_sys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: bs_supermarket_jxc_sys
    password: TMmWJdczNSC5AcSc
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Druid连接池配置
  type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # Redis配置
  redis:
    host: 123.249.43.16
    port: 6379
    database: 0
    password:
    timeout: 3000 # 连接超时时间，单位毫秒
    jedis:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8   # 最大空闲连接数
        min-idle: 0   # 最小空闲连接数
        max-wait: -1  # 最大等待时间，-1 表示不限制

jwt:
  secret: saegfv4asw514egv56ewsfv4asw514egv56ews5fv4asw514egv56ewsv   # 密钥 要长一点不然会报错
  expiration: 10800000   # Token 有效期，单位为毫秒
